[project]
name = "hexlet-code"
version = "0.1.0"
description = "CLI утилита для сравнения конфигурационных файлов"
authors = [{ name = "Anzhelika", email = "darkl11n3ss@gmail.com" }]
readme = "README.md"
dependencies = []
requires-python = ">=3.10"

[tool.setuptools]
packages = ["hexlet_code"]

[tool.hatch.build.targets.wheel]
packages = ["hexlet_code"]

[project.scripts]
gendiff = "hexlet_code.scripts.gendiff:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
