name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv pytest flake8 coverage

      - name: Run linters
        run: make lint

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Install CodeClimate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
          chmod +x cc-test-reporter

      - name: Run tests and collect coverage
        run: |
          ./cc-test-reporter before-build
          coverage run -m pytest
          coverage xml
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}


      - name: Upload coverage to CodeClimate
        run: |
          bash <(curl -s https://codeclimate.com/test-reporter/env)
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

