name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python & uv
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          make setup  # Используем Makefile

      - name: Run linters (flake8)
        run: make lint

      - name: Run tests with coverage
        run: |
          make coverage
          coverage report -m
          coverage xml

      - name: Upload coverage to CodeClimate
        if: success()
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
          chmod +x cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
