name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv & project deps
        run: |
          pip install uv
          make setup

      - name: Run lint check
        run: make lint

      - name: Run tests & generate coverage
        run: make coverage

      - name: Upload coverage to Code Climate
        if: success()
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -Ls https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
          chmod +x cc-test-reporter
          ./cc-test-reporter before-build
          ./cc-test-reporter after-build --exit-code $?
